language: node_js
node_js:
  - '6'

#########################
## Setup
#########################
sudo: true
cache:
  directories:
    - node_modules

install: npm install

script: npm test

after_success:
  - npm run coverage
  - npm run semantic-release
  - npm run reparo

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

#########################
## Deploy
#########################
deploy:
  - edge: true
    skip_cleanup: true
    provider: heroku
    api_key: ${HEROKU_TOKEN}
    app: punchcard-cms
    on:
      branch: master

#########################
## Notifications
#########################
notifications:
  email: false
